# -*- coding: utf-8 -*-
"""Machine Learning Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA0FsY89xJ3nagQHD03n-n6NzRk8O7Ee
"""

print("Hello world")

pip list

import pandas as pd

"""open csv file from url"""

import pandas as pd
url = "https://huggingface.co/datasets/scikit-learn/iris/resolve/main/Iris.csv"
data = pd.read_csv(url)

data

"""EDA

"""

data

"""Info of the dataset

"""

data.head()

data.tail()

data.shape

data.info()

data.describe()

"""checking the missing values

"""

data.isnull().sum()

"""Checking Duplicates

"""

dup=data.drop_duplicates(subset='Species',)
print(dup)

"""Data Visualization"""

# seaborn library
# matplotlib library
import seaborn as sns
import matplotlib.pyplot as plt
# using countplot
sns.countplot(x='Species',data=data)
# results
plt.show()

"""Relation between variables"""

# libraries seaborn & matplotlib
import seaborn as sns
import matplotlib.pyplot as plt
# using scatter plot
sns.scatterplot(x='SepalLengthCm' , y='SepalWidthCm' , hue = 'Species' , data=data)
# results
plt.show()

"""Comparing Petal Length and Petal Width"""

#import packages
import seaborn as sns
import matplotlib.pyplot as plt
#using scatterplot
sns.scatterplot(x='PetalLengthCm' , y='PetalWidthCm' , hue = 'Species' , data=data)
#results
plt.show()

# import packages
import seaborn as sns
import matplotlib.pyplot as plt
# using pairplot
sns.pairplot(data.drop(['Id'], axis=1), hue='Species', height=2)
# results
plt.show()

"""Histograms"""

# importing packages
import seaborn as sns
import matplotlib.pyplot as plt
# histogram
fig, axes = plt.subplots(2,2,figsize=(10,10))
axes[0,0].set_title('Sepal Length')
axes[0,0].hist(data['SepalLengthCm'], bins=7);
axes[0,1].set_title('Sepal Width')
axes[0,1].hist(data['SepalWidthCm'], bins=5);
axes[1,0].set_title('Petal Length')
axes[1,0].hist(data['PetalLengthCm'], bins=6);
axes[1,1].set_title('Petal Width')
axes[1,1].hist(data['PetalWidthCm'], bins =6);

"""Histograms with Distplot Plot"""

# importing packages
import seaborn as sns
import matplotlib.pyplot as plt

plot = sns.FacetGrid(data, hue="Species")
plot.map(sns.distplot, "SepalLengthCm").add_legend()

plot = sns.FacetGrid(data, hue="Species")
plot.map(sns.distplot, "SepalWidthCm").add_legend()

plot = sns.FacetGrid(data, hue="Species")
plot.map(sns.distplot, "PetalLengthCm").add_legend()

plot = sns.FacetGrid(data, hue="Species")
plot.map(sns.distplot, "PetalWidthCm").add_legend()

plt.show()

"""Handling Correlation"""

data.select_dtypes(include=['number']).corr(method='pearson')

"""Heatmaps"""

# importing packages
import seaborn as sns
import matplotlib.pyplot as plt


sns.heatmap(data.select_dtypes(include=['number']).corr(method='pearson').drop(
['Id'], axis=1).drop(['Id'], axis=0),
			annot = True);

plt.show()

"""Box Plots"""

# importing packages
import seaborn as sns
import matplotlib.pyplot as plt

def graph(y):
    sns.boxplot(x="Species", y=y, data=data)

plt.figure(figsize=(10,10))

# Adding the subplot at the specified
# grid position
plt.subplot(221)
graph('SepalLengthCm')

plt.subplot(222)
graph('SepalWidthCm')

plt.subplot(223)
graph('PetalLengthCm')

plt.subplot(224)
graph('PetalWidthCm')

plt.show()

"""Handling Outliers"""

# importing packages
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
data = pd.read_csv(url)

sns.boxplot(x='SepalWidthCm', data=data)

"""Removing Outliers"""

# Importing
import numpy as np

# Load the dataset
df = pd.read_csv(url)

# IQR
Q1 = np.percentile(df['SepalWidthCm'], 25,
				interpolation = 'midpoint')

Q3 = np.percentile(df['SepalWidthCm'], 75,
				interpolation = 'midpoint')
IQR = Q3 - Q1

print("Old Shape: ", df.shape)

# Upper bound
upper = np.where(df['SepalWidthCm'] >= (Q3+1.5*IQR))

# Lower bound
lower = np.where(df['SepalWidthCm'] <= (Q1-1.5*IQR))

# Removing the Outliers
df.drop(upper[0], inplace = True)
df.drop(lower[0], inplace = True)

print("New Shape: ", df.shape)

sns.boxplot(x='SepalWidthCm', data=df)